/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEventFromDiscriminatorValue, createStatusFromDiscriminatorValue, type Event, type Status } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/admissions/{id}
 */
export interface AdmissionsItemRequestBuilder extends BaseRequestBuilder<AdmissionsItemRequestBuilder> {
    /**
     * Get an event by an admission ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Event>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Event | undefined>;
    /**
     * Get an event by an admission ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AdmissionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/admissions/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AdmissionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AdmissionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEventFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
