/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdmissionsItemRequestBuilderRequestsMetadata, type AdmissionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/admissions
 */
export interface AdmissionsRequestBuilder extends BaseRequestBuilder<AdmissionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.admissions.item collection
     * @param id Unique identifier of the item
     * @returns {AdmissionsItemRequestBuilder}
     */
     byId(id: string) : AdmissionsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdmissionsRequestBuilderUriTemplate = "{+baseurl}/v1/admissions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdmissionsRequestBuilderNavigationMetadata: Record<Exclude<keyof AdmissionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AdmissionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
