/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAttendeeFromDiscriminatorValue, createStatusFromDiscriminatorValue, type Attendee, type Status } from '../../../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/events/{id}/attendees/{attendeeId}
 */
export interface WithAttendeeItemRequestBuilder extends BaseRequestBuilder<WithAttendeeItemRequestBuilder> {
    /**
     * Admit event attendee
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Attendee>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Attendee | undefined>;
    /**
     * Admit event attendee
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithAttendeeItemRequestBuilderUriTemplate = "{+baseurl}/v1/events/{id}/attendees/{attendeeId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithAttendeeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithAttendeeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAttendeeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
