/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { VerifyRequestBuilderRequestsMetadata, type VerifyRequestBuilder } from './verify/index.js';
// @ts-ignore
import { WhoAmIRequestBuilderRequestsMetadata, type WhoAmIRequestBuilder } from './whoAmI/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The Verify property
     */
    get verify(): VerifyRequestBuilder;
    /**
     * The WhoAmI property
     */
    get whoAmI(): WhoAmIRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/Auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    verify: {
        requestsMetadata: VerifyRequestBuilderRequestsMetadata,
    },
    whoAmI: {
        requestsMetadata: WhoAmIRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
