/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse } from '../../models/index.js';
// @ts-ignore
import { AttendeeRequestBuilderRequestsMetadata, type AttendeeRequestBuilder } from './attendee/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event/{id}
 */
export interface EventItemRequestBuilder extends BaseRequestBuilder<EventItemRequestBuilder> {
    /**
     * The Attendee property
     */
    get attendee(): AttendeeRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EventItemRequestBuilderUriTemplate = "{+baseurl}/Event/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EventItemRequestBuilderNavigationMetadata: Record<Exclude<keyof EventItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attendee: {
        requestsMetadata: AttendeeRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EventItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EventItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
