/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsUserUserResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth/WhoAmI
 */
export interface WhoAmIRequestBuilder extends BaseRequestBuilder<WhoAmIRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WhoAmIRequestBuilderUriTemplate = "{+baseurl}/Auth/WhoAmI";
/**
 * Metadata for all the requests in the request builder.
 */
export const WhoAmIRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WhoAmIRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsUserUserResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
