/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationCoreDtosUserAlumniMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserEmployeeMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserEmployeeResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserServiceAccountResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserSystemAdminResponseFromDiscriminatorValue, deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse, serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse, serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse, serializeSSTAlumniAssociationCoreDtosUserMemberResponse, serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse, serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse, type SSTAlumniAssociationCoreDtosUserAlumniMemberResponse, type SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, type SSTAlumniAssociationCoreDtosUserEmployeeResponse, type SSTAlumniAssociationCoreDtosUserMemberResponse, type SSTAlumniAssociationCoreDtosUserServiceAccountResponse, type SSTAlumniAssociationCoreDtosUserSystemAdminResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse}
 */
// @ts-ignore
export function createWhoAmIGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    const mappingValueNode = parseNode?.getChildNode("discriminator");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "SSTAlumniAssociationCoreDtosUserAlumniMemberResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse;
                case "SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse;
                case "SSTAlumniAssociationCoreDtosUserEmployeeResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse;
                case "SSTAlumniAssociationCoreDtosUserMemberResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse;
                case "SSTAlumniAssociationCoreDtosUserServiceAccountResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse;
                case "SSTAlumniAssociationCoreDtosUserSystemAdminResponse":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse;
            }
        }
    }
    return deserializeIntoWhoAmIGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWhoAmIGetResponse(whoAmIGetResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserEmployeeResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserServiceAccountResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse(whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserSystemAdminResponse),
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWhoAmIGetResponse(writer: SerializationWriter, whoAmIGetResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined | null = {}) : void {
    if (whoAmIGetResponse === undefined || whoAmIGetResponse === null) return;
    switch (whoAmIGetResponse.discriminator) {
        case "SSTAlumniAssociationCoreDtosUserAlumniMemberResponse":
            serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse);
            break;
        case "SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse);
            break;
        case "SSTAlumniAssociationCoreDtosUserEmployeeResponse":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserEmployeeResponse);
            break;
        case "SSTAlumniAssociationCoreDtosUserMemberResponse":
            serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserMemberResponse);
            break;
        case "SSTAlumniAssociationCoreDtosUserServiceAccountResponse":
            serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserServiceAccountResponse);
            break;
        case "SSTAlumniAssociationCoreDtosUserSystemAdminResponse":
            serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse(writer, whoAmIGetResponse as SSTAlumniAssociationCoreDtosUserSystemAdminResponse);
            break;
    }
}
export type WhoAmIGetResponse = SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse;
/**
 * Builds and executes requests for operations under /Auth/WhoAmI
 */
export interface WhoAmIRequestBuilder extends BaseRequestBuilder<WhoAmIRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WhoAmIRequestBuilderUriTemplate = "{+baseurl}/Auth/WhoAmI";
/**
 * Metadata for all the requests in the request builder.
 */
export const WhoAmIRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WhoAmIRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWhoAmIGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
