/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createSSTAlumniAssociationAdminWebApiEndpointsEventEventResponseFromDiscriminatorValue, serializeSSTAlumniAssociationAdminWebApiEndpointsEventEventResponse, serializeSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest, type FastEndpointsErrorResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest } from '../../models/index.js';
// @ts-ignore
import { AttendeeRequestBuilderRequestsMetadata, type AttendeeRequestBuilder } from './attendee/index.js';
// @ts-ignore
import { AttendeeBatchRequestBuilderRequestsMetadata, type AttendeeBatchRequestBuilder } from './attendeeBatch/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event/{-id}
 */
export interface ItemRequestBuilder extends BaseRequestBuilder<ItemRequestBuilder> {
    /**
     * The Attendee property
     */
    get attendee(): AttendeeRequestBuilder;
    /**
     * The AttendeeBatch property
     */
    get attendeeBatch(): AttendeeBatchRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ItemRequestBuilderUriTemplate = "{+baseurl}/Event/{%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attendee: {
        requestsMetadata: AttendeeRequestBuilderRequestsMetadata,
    },
    attendeeBatch: {
        requestsMetadata: AttendeeBatchRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsEventEventResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsEventEventResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
