/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListArticlesResponseFromDiscriminatorValue, createStatusFromDiscriminatorValue, serializeListArticlesRequest, serializeListArticlesResponse, type ListArticlesRequest, type ListArticlesResponse, type Status } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/articles
 */
export interface ArticlesRequestBuilder extends BaseRequestBuilder<ArticlesRequestBuilder> {
    /**
     * List all articles
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListArticlesResponse>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     post(body: ListArticlesRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ListArticlesResponse | undefined>;
    /**
     * List all articles
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ListArticlesRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ArticlesRequestBuilderUriTemplate = "{+baseurl}/v1/articles";
/**
 * Metadata for all the requests in the request builder.
 */
export const ArticlesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ArticlesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createListArticlesResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeListArticlesRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
