/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Any extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The Type property
     */
    type?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Any}
 */
export function createAnyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAny;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Status}
 */
export function createStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStatus;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {User}
 */
export function createUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUser;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoAny(any: Partial<Any> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "@type": n => { any.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoStatus(status: Partial<Status> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { status.code = n.getNumberValue(); },
        "details": n => { status.details = n.getCollectionOfObjectValues<Any>(createAnyFromDiscriminatorValue); },
        "message": n => { status.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoUser(user: Partial<User> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { user.email = n.getStringValue(); },
        "id": n => { user.id = n.getStringValue(); },
        "name": n => { user.name = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeAny(writer: SerializationWriter, any: Partial<Any> | undefined = {}) : void {
    writer.writeStringValue("@type", any.type);
    writer.writeAdditionalData(any.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeStatus(writer: SerializationWriter, status: Partial<Status> | undefined = {}) : void {
    writer.writeNumberValue("code", status.code);
    writer.writeCollectionOfObjectValues<Any>("details", status.details, serializeAny);
    writer.writeStringValue("message", status.messageEscaped);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeUser(writer: SerializationWriter, user: Partial<User> | undefined = {}) : void {
    writer.writeStringValue("email", user.email);
    writer.writeStringValue("id", user.id);
    writer.writeStringValue("name", user.name);
}
export interface Status extends ApiError, Parsable {
    /**
     * The code property
     */
    code?: number;
    /**
     * The details property
     */
    details?: Any[];
    /**
     * The message property
     */
    messageEscaped?: string;
}
export interface User extends Parsable {
    /**
     * The email property
     */
    email?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The name property
     */
    name?: string;
}
/* tslint:enable */
/* eslint-enable */
