/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponseFromDiscriminatorValue, serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest, serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse, type SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest, type SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth/Verify
 */
export interface VerifyRequestBuilder extends BaseRequestBuilder<VerifyRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse>}
     */
     post(body: SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VerifyRequestBuilderUriTemplate = "{+baseurl}/Auth/Verify";
/**
 * Metadata for all the requests in the request builder.
 */
export const VerifyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: VerifyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
