/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponseFromDiscriminatorValue, serializeSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse, serializeSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest, type FastEndpointsErrorResponse, type SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse, type SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Article
 */
export interface ArticleRequestBuilder extends BaseRequestBuilder<ArticleRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ArticleRequestBuilderUriTemplate = "{+baseurl}/Article";
/**
 * Metadata for all the requests in the request builder.
 */
export const ArticleRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ArticleRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ArticleRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
