/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue, type SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /CheckIn
 */
export interface CheckInRequestBuilder extends BaseRequestBuilder<CheckInRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckInRequestBuilderUriTemplate = "{+baseurl}/CheckIn";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckInRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckInRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
