/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationCoreDtosUserAlumniMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserEmployeeMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserEmployeeResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserMemberResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserServiceAccountResponseFromDiscriminatorValue, createSSTAlumniAssociationCoreDtosUserSystemAdminResponseFromDiscriminatorValue, deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse, deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse, serializeSSTAlumniAssociationAdminWebApiEndpointsUserBatchCreateBatchCreateUserRequest, serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse, serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse, serializeSSTAlumniAssociationCoreDtosUserMemberResponse, serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse, serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse, type SSTAlumniAssociationAdminWebApiEndpointsUserBatchCreateBatchCreateUserRequest, type SSTAlumniAssociationCoreDtosUserAlumniMemberResponse, type SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse, type SSTAlumniAssociationCoreDtosUserEmployeeResponse, type SSTAlumniAssociationCoreDtosUserMemberResponse, type SSTAlumniAssociationCoreDtosUserServiceAccountResponse, type SSTAlumniAssociationCoreDtosUserSystemAdminResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    const mappingValueNode = parseNode?.getChildNode("discriminator");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "AlumniMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse;
                case "Employee":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse;
                case "EmployeeMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse;
                case "Member":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse;
                case "ServiceAccount":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse;
                case "SystemAdmin":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse;
            }
        }
    }
    return deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserUserResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserEmployeeResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserServiceAccountResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse(sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserSystemAdminResponse),
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserUserResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserUserResponse === undefined || sSTAlumniAssociationCoreDtosUserUserResponse === null) return;
    switch (sSTAlumniAssociationCoreDtosUserUserResponse.discriminator) {
        case "AlumniMember":
            serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse);
            break;
        case "Employee":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserEmployeeResponse);
            break;
        case "EmployeeMember":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse);
            break;
        case "Member":
            serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserMemberResponse);
            break;
        case "ServiceAccount":
            serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserServiceAccountResponse);
            break;
        case "SystemAdmin":
            serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponse as SSTAlumniAssociationCoreDtosUserSystemAdminResponse);
            break;
    }
}
export type SSTAlumniAssociationCoreDtosUserUserResponse = SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse;
/**
 * Builds and executes requests for operations under /User:Batch
 */
export interface UserBatchRequestBuilder extends BaseRequestBuilder<UserBatchRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<(SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse)[]>}
     */
     post(body: SSTAlumniAssociationAdminWebApiEndpointsUserBatchCreateBatchCreateUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<(SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse)[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationAdminWebApiEndpointsUserBatchCreateBatchCreateUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UserBatchRequestBuilderUriTemplate = "{+baseurl}/User:Batch";
/**
 * Metadata for all the requests in the request builder.
 */
export const UserBatchRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UserBatchRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationCoreDtosUserUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationAdminWebApiEndpointsUserBatchCreateBatchCreateUserRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
