/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue, createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequestFromDiscriminatorValue, createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequestFromDiscriminatorValue, deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest, deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest, serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse, serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest, serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest, type SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse, type SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest, type SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest } from '../models/index.js';
// @ts-ignore
import { CheckInItemRequestBuilderNavigationMetadata, type CheckInItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /CheckIn
 */
export interface CheckInRequestBuilder extends BaseRequestBuilder<CheckInRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.CheckIn.item collection
     * @param id Unique identifier of the item
     * @returns {CheckInItemRequestBuilder}
     */
     byId(id: string) : CheckInItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse>}
     */
     post(body: SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    const mappingValueNode = parseNode?.getChildNode("type");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "Guest":
                    return deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest;
                case "User":
                    return deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest;
            }
        }
    }
    return deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest(sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest: Partial<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest(sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest as SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest),
        ...deserializeIntoSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest(sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest as SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest),
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest(writer: SerializationWriter, sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest: Partial<SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest === undefined || sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest === null) return;
    switch (sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest.type) {
        case "Guest":
            serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest(writer, sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest as SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest);
            break;
        case "User":
            serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest(writer, sSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest as SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest);
            break;
    }
}
export type SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest = SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateGuestCheckInRequest | SSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateUserCheckInRequest;
/**
 * Uri template for the request builder.
 */
export const CheckInRequestBuilderUriTemplate = "{+baseurl}/CheckIn";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CheckInRequestBuilderNavigationMetadata: Record<Exclude<keyof CheckInRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        navigationMetadata: CheckInItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["Id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckInRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckInRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: CheckInRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationServiceAccountWebApiEndpointsCheckInCreateCheckInRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
