/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue, serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse, serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest, type FastEndpointsErrorResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event/{-id}/Attendee
 */
export interface AttendeeRequestBuilder extends BaseRequestBuilder<AttendeeRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AttendeeRequestBuilderUriTemplate = "{+baseurl}/Event/{%2Did}/Attendee";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttendeeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AttendeeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AttendeeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
