/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListCheckInsResponseFromDiscriminatorValue, createStatusFromDiscriminatorValue, type ListCheckInsResponse, type Status } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/check-ins
 */
export interface CheckInsRequestBuilder extends BaseRequestBuilder<CheckInsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListCheckInsResponse>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<CheckInsRequestBuilderGetQueryParameters> | undefined) : Promise<ListCheckInsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CheckInsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface CheckInsRequestBuilderGetQueryParameters {
    checkedOut?: string;
    checkInDate?: string;
    checkOutDate?: string;
    pageSize?: string;
    pageToken?: string;
    serviceAccount?: string;
}
/**
 * Uri template for the request builder.
 */
export const CheckInsRequestBuilderUriTemplate = "{+baseurl}/v1/check-ins{?checkInDate*,checkOutDate*,checkedOut*,pageSize*,pageToken*,serviceAccount*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckInsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckInsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createListCheckInsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
