/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Attendee/{AttendeeId}
 */
export interface WithAttendeeItemRequestBuilder extends BaseRequestBuilder<WithAttendeeItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithAttendeeItemRequestBuilderUriTemplate = "{+baseurl}/Attendee/{AttendeeId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithAttendeeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithAttendeeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
