/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse_errors}
 */
// @ts-ignore
export function createFastEndpointsErrorResponse_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse}
 */
// @ts-ignore
export function createFastEndpointsErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventEventResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventEventResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    const mappingValueNode = parseNode?.getChildNode("$type");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "AlumniMember":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest;
                case "Employee":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest;
                case "EmployeeMember":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest;
                case "ServiceAccount":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest;
                case "SystemAdmin":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest;
                case "_member":
                    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest;
            }
        }
    }
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationAdminWebApiEndpointsUserUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserUserResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse(fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { fastEndpointsErrorResponse.errors = n.getObjectValue<FastEndpointsErrorResponse_errors>(createFastEndpointsErrorResponse_errorsFromDiscriminatorValue); },
        "message": n => { fastEndpointsErrorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "statusCode": n => { fastEndpointsErrorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse_errors(fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse(sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ctaTitle": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.ctaTitle = n.getStringValue(); },
        "ctaUrl": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.ctaUrl = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.description = n.getStringValue(); },
        "heroImageAlt": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.heroImageAlt = n.getStringValue(); },
        "heroImageUrl": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.heroImageUrl = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.id = n.getStringValue(); },
        "title": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest(sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ctaTitle": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.ctaTitle = n.getStringValue(); },
        "ctaUrl": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.ctaUrl = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.description = n.getStringValue(); },
        "heroImageAlt": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.heroImageAlt = n.getStringValue(); },
        "heroImageUrl": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.heroImageUrl = n.getStringValue(); },
        "title": n => { sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse(sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "checkInDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.checkInDateTime = n.getDateValue(); },
        "checkOutDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.checkOutDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.id = n.getStringValue(); },
        "serviceAccountId": n => { sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.serviceAccountId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse(sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "admissionKey": n => { sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.admissionKey = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.id = n.getStringValue(); },
        "user": n => { sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.user = n.getObjectValue<SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse>(createSSTAlumniAssociationAdminWebApiEndpointsUserUserResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest(sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "userIds": n => { sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest.userIds = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest(sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "userId": n => { sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest.userId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest(sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.active = n.getBooleanValue(); },
        "badgeImage": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.badgeImage = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.description = n.getStringValue(); },
        "endDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.endDateTime = n.getDateValue(); },
        "location": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.location = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.name = n.getStringValue(); },
        "startDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventEventResponse(sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.active = n.getBooleanValue(); },
        "badgeImage": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.badgeImage = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.description = n.getStringValue(); },
        "endDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.endDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.id = n.getStringValue(); },
        "location": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.location = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.name = n.getStringValue(); },
        "startDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest(sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.active = n.getBooleanValue(); },
        "badgeImage": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.badgeImage = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.description = n.getStringValue(); },
        "endDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.endDateTime = n.getDateValue(); },
        "location": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.location = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.name = n.getStringValue(); },
        "startDateTime": n => { sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest),
        "graduationYear": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest.graduationYear = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest),
        "graduationYear": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest.graduationYear = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest),
        "memberId": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest.memberId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest),
        "serviceAccountType": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest.serviceAccountType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.email = n.getStringValue(); },
        "firebaseId": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.firebaseId = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.name = n.getStringValue(); },
        "$type": n => { sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationAdminWebApiEndpointsUserUserResponse(sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.email = n.getStringValue(); },
        "firebaseId": n => { sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.firebaseId = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.id = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.name = n.getStringValue(); },
        "revoked": n => { sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.revoked = n.getBooleanValue(); },
    }
}
export interface FastEndpointsErrorResponse extends ApiError, Parsable {
    /**
     * The errors property
     */
    errors?: FastEndpointsErrorResponse_errors | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
}
export interface FastEndpointsErrorResponse_errors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse(writer: SerializationWriter, fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse) {
        writer.writeObjectValue<FastEndpointsErrorResponse_errors>("errors", fastEndpointsErrorResponse.errors, serializeFastEndpointsErrorResponse_errors);
        writer.writeStringValue("message", fastEndpointsErrorResponse.messageEscaped ?? "One or more errors occurred!");
        writer.writeNumberValue("statusCode", fastEndpointsErrorResponse.statusCode);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse_errors(writer: SerializationWriter, fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse_errors) {
        writer.writeAdditionalData(fastEndpointsErrorResponse_errors.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse) {
        writer.writeStringValue("ctaTitle", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.ctaTitle);
        writer.writeStringValue("ctaUrl", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.ctaUrl);
        writer.writeStringValue("description", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.description);
        writer.writeStringValue("heroImageAlt", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.heroImageAlt);
        writer.writeStringValue("heroImageUrl", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.heroImageUrl);
        writer.writeStringValue("id", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.id);
        writer.writeStringValue("title", sSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest) {
        writer.writeStringValue("ctaTitle", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.ctaTitle);
        writer.writeStringValue("ctaUrl", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.ctaUrl);
        writer.writeStringValue("description", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.description);
        writer.writeStringValue("heroImageAlt", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.heroImageAlt);
        writer.writeStringValue("heroImageUrl", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.heroImageUrl);
        writer.writeStringValue("title", sSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse) {
        writer.writeDateValue("checkInDateTime", sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.checkInDateTime);
        writer.writeDateValue("checkOutDateTime", sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.checkOutDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.id);
        writer.writeStringValue("serviceAccountId", sSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse.serviceAccountId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse) {
        writer.writeStringValue("admissionKey", sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.admissionKey);
        writer.writeStringValue("id", sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.id);
        writer.writeObjectValue<SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse>("user", sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse.user, serializeSSTAlumniAssociationAdminWebApiEndpointsUserUserResponse);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest) {
        writer.writeCollectionOfPrimitiveValues<string>("userIds", sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest.userIds);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest) {
        writer.writeStringValue("userId", sSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest.userId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest) {
        writer.writeBooleanValue("active", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.active);
        writer.writeStringValue("badgeImage", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.badgeImage);
        writer.writeStringValue("description", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.description);
        writer.writeDateValue("endDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.endDateTime);
        writer.writeStringValue("location", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.location);
        writer.writeStringValue("name", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.name);
        writer.writeDateValue("startDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventEventResponse(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse) {
        writer.writeBooleanValue("active", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.active);
        writer.writeStringValue("badgeImage", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.badgeImage);
        writer.writeStringValue("description", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.description);
        writer.writeDateValue("endDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.endDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.id);
        writer.writeStringValue("location", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.location);
        writer.writeStringValue("name", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.name);
        writer.writeDateValue("startDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventEventResponse.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest) {
        writer.writeBooleanValue("active", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.active);
        writer.writeStringValue("badgeImage", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.badgeImage);
        writer.writeStringValue("description", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.description);
        writer.writeDateValue("endDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.endDateTime);
        writer.writeStringValue("location", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.location);
        writer.writeStringValue("name", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.name);
        writer.writeDateValue("startDateTime", sSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest)
        writer.writeNumberValue("graduationYear", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest.graduationYear);
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest)
        writer.writeNumberValue("graduationYear", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest.graduationYear);
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest)
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest)
        writer.writeStringValue("memberId", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest.memberId);
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest)
        writer.writeNumberValue("serviceAccountType", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest.serviceAccountType);
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest) {
        serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(writer, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest)
        writer.writeAdditionalData(sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest) {
        writer.writeStringValue("email", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.email);
        writer.writeStringValue("firebaseId", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.firebaseId);
        writer.writeStringValue("name", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.name);
        writer.writeStringValue("$type", sSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest.type);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationAdminWebApiEndpointsUserUserResponse(writer: SerializationWriter, sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse: Partial<SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse) {
        writer.writeStringValue("email", sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.email);
        writer.writeStringValue("firebaseId", sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.firebaseId);
        writer.writeStringValue("id", sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.id);
        writer.writeStringValue("name", sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.name);
        writer.writeBooleanValue("revoked", sSTAlumniAssociationAdminWebApiEndpointsUserUserResponse.revoked);
    }
}
export interface SSTAlumniAssociationAdminWebApiEndpointsArticleArticleResponse extends Parsable {
    /**
     * The ctaTitle property
     */
    ctaTitle?: string | null;
    /**
     * The ctaUrl property
     */
    ctaUrl?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The heroImageAlt property
     */
    heroImageAlt?: string | null;
    /**
     * The heroImageUrl property
     */
    heroImageUrl?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsArticleCreateCreateArticleRequest extends Parsable {
    /**
     * The ctaTitle property
     */
    ctaTitle?: string | null;
    /**
     * The ctaUrl property
     */
    ctaUrl?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The heroImageAlt property
     */
    heroImageAlt?: string | null;
    /**
     * The heroImageUrl property
     */
    heroImageUrl?: string | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsCheckInCheckInResponse extends Parsable {
    /**
     * The checkInDateTime property
     */
    checkInDateTime?: Date | null;
    /**
     * The checkOutDateTime property
     */
    checkOutDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The serviceAccountId property
     */
    serviceAccountId?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse extends Parsable {
    /**
     * The admissionKey property
     */
    admissionKey?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The user property
     */
    user?: SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest extends Parsable {
    /**
     * The userIds property
     */
    userIds?: string[] | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeCreateCreateEventAttendeeRequest extends Parsable {
    /**
     * The userId property
     */
    userId?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventCreateCreateEventRequest extends Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The badgeImage property
     */
    badgeImage?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventEventResponse extends Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The badgeImage property
     */
    badgeImage?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsEventUpdateUpdateEventRequest extends Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The badgeImage property
     */
    badgeImage?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateAlumniMemberRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The graduationYear property
     */
    graduationYear?: number | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeMemberRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The graduationYear property
     */
    graduationYear?: number | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateEmployeeRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateMemberRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The memberId property
     */
    memberId?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateServiceAccountRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The serviceAccountType property
     */
    serviceAccountType?: number | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateSystemAdminRequest extends AdditionalDataHolder, Parsable, SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserCreateCreateUserRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The firebaseId property
     */
    firebaseId?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * This accepts- EmployeeMember- AlumniMember- Employee- SystemAdmin- ServiceAccount
     */
    type?: string | null;
}
export interface SSTAlumniAssociationAdminWebApiEndpointsUserUserResponse extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The firebaseId property
     */
    firebaseId?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The revoked property
     */
    revoked?: boolean | null;
}
/* tslint:enable */
/* eslint-enable */
