/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type VerifyRequestBuilder, VerifyRequestBuilderRequestsMetadata } from './verify/';
// @ts-ignore
import { type WhoamiRequestBuilder, WhoamiRequestBuilderRequestsMetadata } from './whoami/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The verify property
     */
    get verify(): VerifyRequestBuilder;
    /**
     * The whoami property
     */
    get whoami(): WhoamiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/v1/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    verify: {
        requestsMetadata: VerifyRequestBuilderRequestsMetadata,
    },
    whoami: {
        requestsMetadata: WhoamiRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
