/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createStatusFromDiscriminatorValue, createVerifyUserResponseFromDiscriminatorValue, serializeVerifyUserRequest, serializeVerifyUserResponse, type Status, type VerifyUserRequest, type VerifyUserResponse } from '../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/auth/verify
 */
export interface VerifyRequestBuilder extends BaseRequestBuilder<VerifyRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VerifyUserResponse>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     post(body: VerifyUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VerifyUserResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: VerifyUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VerifyRequestBuilderUriTemplate = "{+baseurl}/v1/auth/verify";
/**
 * Metadata for all the requests in the request builder.
 */
export const VerifyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: VerifyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVerifyUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVerifyUserRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
