/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue, serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse, serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest, type FastEndpointsErrorResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse, type SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event/{-id}/Attendee:Batch
 */
export interface AttendeeBatchRequestBuilder extends BaseRequestBuilder<AttendeeBatchRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse[]>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AttendeeBatchRequestBuilderUriTemplate = "{+baseurl}/Event/{%2Did}/Attendee:Batch";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttendeeBatchRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AttendeeBatchRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeAttendeeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSSTAlumniAssociationAdminWebApiEndpointsEventAttendeeBatchCreateBatchCreateEventAttendeeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
