/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsUserUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsUserUserResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest(sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse(sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.id = n.getStringValue(); },
        "linked": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.linked = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse(sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "checkInDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkInDateTime = n.getDateValue(); },
        "checkOutDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkOutDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsUserUserResponse(sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.email = n.getStringValue(); },
        "firebaseId": n => { sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.firebaseId = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.id = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.name = n.getStringValue(); },
        "revoked": n => { sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.revoked = n.getBooleanValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest) {
        writer.writeStringValue("email", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest.email);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse) {
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.id);
        writer.writeBooleanValue("linked", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.linked);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse) {
        writer.writeDateValue("checkInDateTime", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkInDateTime);
        writer.writeDateValue("checkOutDateTime", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkOutDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsUserUserResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse) {
        writer.writeStringValue("email", sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.email);
        writer.writeStringValue("firebaseId", sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.firebaseId);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.id);
        writer.writeStringValue("name", sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.name);
        writer.writeBooleanValue("revoked", sSTAlumniAssociationMemberWebApiEndpointsUserUserResponse.revoked);
    }
}
export interface SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The linked property
     */
    linked?: boolean | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse extends Parsable {
    /**
     * The checkInDateTime property
     */
    checkInDateTime?: Date | null;
    /**
     * The checkOutDateTime property
     */
    checkOutDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The firebaseId property
     */
    firebaseId?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The revoked property
     */
    revoked?: boolean | null;
}
/* tslint:enable */
/* eslint-enable */
