/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserAlumniMemberResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserAlumniMemberResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserEmployeeMemberResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserEmployeeResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserEmployeeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserMemberResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserMemberResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserMembershipPlanResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserMembershipPlanResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserMembershipPlanResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserServiceAccountResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserServiceAccountResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserSystemAdminResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserSystemAdminResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserUserResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    const mappingValueNode = parseNode?.getChildNode("discriminator");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "AlumniMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse;
                case "Employee":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse;
                case "EmployeeMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse;
                case "Member":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse;
                case "ServiceAccount":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse;
                case "SystemAdmin":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse;
            }
        }
    }
    return deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationCoreDtosUserUserResponseWrapperFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    const mappingValueNode = parseNode?.getChildNode("discriminator");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "AlumniMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse;
                case "Employee":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse;
                case "EmployeeMember":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse;
                case "Member":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse;
                case "ServiceAccount":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse;
                case "SystemAdmin":
                    return deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse;
            }
        }
    }
    return deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponseWrapper;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse}
 */
// @ts-ignore
export function createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsEventEventResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(sSTAlumniAssociationCoreDtosUserAlumniMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(sSTAlumniAssociationCoreDtosUserAlumniMemberResponse),
        "graduationYear": n => { sSTAlumniAssociationCoreDtosUserAlumniMemberResponse.graduationYear = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse),
        "graduationYear": n => { sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse.graduationYear = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse(sSTAlumniAssociationCoreDtosUserEmployeeResponse: Partial<SSTAlumniAssociationCoreDtosUserEmployeeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserEmployeeResponse),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(sSTAlumniAssociationCoreDtosUserMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserMemberResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserMemberResponse),
        "activeSubscription": n => { sSTAlumniAssociationCoreDtosUserMemberResponse.activeSubscription = n.getObjectValue<SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse>(createSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponseFromDiscriminatorValue); },
        "memberId": n => { sSTAlumniAssociationCoreDtosUserMemberResponse.memberId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserMembershipPlanResponse(sSTAlumniAssociationCoreDtosUserMembershipPlanResponse: Partial<SSTAlumniAssociationCoreDtosUserMembershipPlanResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "builtIn": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.builtIn = n.getBooleanValue(); },
        "description": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.description = n.getStringValue(); },
        "duration": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.duration = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.id = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.name = n.getStringValue(); },
        "price": n => { sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.price = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse(sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse: Partial<SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "endDateTime": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.endDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.id = n.getStringValue(); },
        "membershipPlan": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.membershipPlan = n.getObjectValue<SSTAlumniAssociationCoreDtosUserMembershipPlanResponse>(createSSTAlumniAssociationCoreDtosUserMembershipPlanResponseFromDiscriminatorValue); },
        "paymentIntentId": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.paymentIntentId = n.getStringValue(); },
        "paymentIntentState": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.paymentIntentState = n.getNumberValue(); },
        "startDateTime": n => { sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse(sSTAlumniAssociationCoreDtosUserServiceAccountResponse: Partial<SSTAlumniAssociationCoreDtosUserServiceAccountResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserServiceAccountResponse),
        "serviceAccountType": n => { sSTAlumniAssociationCoreDtosUserServiceAccountResponse.serviceAccountType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse(sSTAlumniAssociationCoreDtosUserSystemAdminResponse: Partial<SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserSystemAdminResponse),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponse(sSTAlumniAssociationCoreDtosUserUserResponse: Partial<SSTAlumniAssociationCoreDtosUserUserResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "discriminator": n => { sSTAlumniAssociationCoreDtosUserUserResponse.discriminator = n.getStringValue(); },
        "email": n => { sSTAlumniAssociationCoreDtosUserUserResponse.email = n.getStringValue(); },
        "firebaseId": n => { sSTAlumniAssociationCoreDtosUserUserResponse.firebaseId = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationCoreDtosUserUserResponse.id = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationCoreDtosUserUserResponse.name = n.getStringValue(); },
        "revoked": n => { sSTAlumniAssociationCoreDtosUserUserResponse.revoked = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationCoreDtosUserUserResponseWrapper(sSTAlumniAssociationCoreDtosUserUserResponseWrapper: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserEmployeeResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserEmployeeResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserMemberResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserMemberResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserServiceAccountResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserServiceAccountResponse),
        ...deserializeIntoSSTAlumniAssociationCoreDtosUserSystemAdminResponse(sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserSystemAdminResponse),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse(sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ctaTitle": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.ctaTitle = n.getStringValue(); },
        "ctaUrl": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.ctaUrl = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.description = n.getStringValue(); },
        "heroImageAlt": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.heroImageAlt = n.getStringValue(); },
        "heroImageUrl": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.heroImageUrl = n.getStringValue(); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.id = n.getStringValue(); },
        "title": n => { sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse(sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "admissionKey": n => { sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admissionKey = n.getStringValue(); },
        "admittedAt": n => { sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admittedAt = n.getDateValue(); },
        "admittedBy": n => { sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admittedBy = n.getObjectValue<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse>(createSSTAlumniAssociationCoreDtosUserAlumniMemberResponseFromDiscriminatorValue) ?? n.getObjectValue<SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse>(createSSTAlumniAssociationCoreDtosUserEmployeeMemberResponseFromDiscriminatorValue) ?? n.getObjectValue<SSTAlumniAssociationCoreDtosUserEmployeeResponse>(createSSTAlumniAssociationCoreDtosUserEmployeeResponseFromDiscriminatorValue) ?? n.getObjectValue<SSTAlumniAssociationCoreDtosUserMemberResponse>(createSSTAlumniAssociationCoreDtosUserMemberResponseFromDiscriminatorValue) ?? n.getObjectValue<SSTAlumniAssociationCoreDtosUserServiceAccountResponse>(createSSTAlumniAssociationCoreDtosUserServiceAccountResponseFromDiscriminatorValue) ?? n.getObjectValue<SSTAlumniAssociationCoreDtosUserSystemAdminResponse>(createSSTAlumniAssociationCoreDtosUserSystemAdminResponseFromDiscriminatorValue); },
        "event": n => { sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.event = n.getObjectValue<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse>(createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest(sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse(sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.id = n.getStringValue(); },
        "linked": n => { sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.linked = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse(sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "checkInDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkInDateTime = n.getDateValue(); },
        "checkOutDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkOutDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSSTAlumniAssociationMemberWebApiEndpointsEventEventResponse(sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "active": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.active = n.getBooleanValue(); },
        "badgeImage": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.badgeImage = n.getStringValue(); },
        "description": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.description = n.getStringValue(); },
        "endDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.endDateTime = n.getDateValue(); },
        "id": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.id = n.getStringValue(); },
        "location": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.location = n.getStringValue(); },
        "name": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.name = n.getStringValue(); },
        "startDateTime": n => { sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserAlumniMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserAlumniMemberResponse) {
        serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer, sSTAlumniAssociationCoreDtosUserAlumniMemberResponse)
        writer.writeNumberValue("graduationYear", sSTAlumniAssociationCoreDtosUserAlumniMemberResponse.graduationYear);
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserAlumniMemberResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse) {
        serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer, sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse)
        writer.writeNumberValue("graduationYear", sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse.graduationYear);
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserEmployeeMemberResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserEmployeeResponse: Partial<SSTAlumniAssociationCoreDtosUserEmployeeResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserEmployeeResponse) {
        serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer, sSTAlumniAssociationCoreDtosUserEmployeeResponse)
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserEmployeeResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserMemberResponse: Partial<SSTAlumniAssociationCoreDtosUserMemberResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserMemberResponse) {
        serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer, sSTAlumniAssociationCoreDtosUserMemberResponse)
        writer.writeObjectValue<SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse>("activeSubscription", sSTAlumniAssociationCoreDtosUserMemberResponse.activeSubscription, serializeSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse);
        writer.writeStringValue("memberId", sSTAlumniAssociationCoreDtosUserMemberResponse.memberId);
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserMemberResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserMembershipPlanResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserMembershipPlanResponse: Partial<SSTAlumniAssociationCoreDtosUserMembershipPlanResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserMembershipPlanResponse) {
        writer.writeBooleanValue("builtIn", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.builtIn);
        writer.writeStringValue("description", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.description);
        writer.writeStringValue("duration", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.duration);
        writer.writeStringValue("id", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.id);
        writer.writeStringValue("name", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.name);
        writer.writeNumberValue("price", sSTAlumniAssociationCoreDtosUserMembershipPlanResponse.price);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse: Partial<SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse) {
        writer.writeDateValue("endDateTime", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.endDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.id);
        writer.writeObjectValue<SSTAlumniAssociationCoreDtosUserMembershipPlanResponse>("membershipPlan", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.membershipPlan, serializeSSTAlumniAssociationCoreDtosUserMembershipPlanResponse);
        writer.writeStringValue("paymentIntentId", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.paymentIntentId);
        writer.writeNumberValue("paymentIntentState", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.paymentIntentState);
        writer.writeDateValue("startDateTime", sSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserServiceAccountResponse: Partial<SSTAlumniAssociationCoreDtosUserServiceAccountResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserServiceAccountResponse) {
        serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer, sSTAlumniAssociationCoreDtosUserServiceAccountResponse)
        writer.writeNumberValue("serviceAccountType", sSTAlumniAssociationCoreDtosUserServiceAccountResponse.serviceAccountType);
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserServiceAccountResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserSystemAdminResponse: Partial<SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserSystemAdminResponse) {
        serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer, sSTAlumniAssociationCoreDtosUserSystemAdminResponse)
        writer.writeAdditionalData(sSTAlumniAssociationCoreDtosUserSystemAdminResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserUserResponse(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserUserResponse: Partial<SSTAlumniAssociationCoreDtosUserUserResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserUserResponse) {
        writer.writeStringValue("discriminator", sSTAlumniAssociationCoreDtosUserUserResponse.discriminator);
        writer.writeStringValue("email", sSTAlumniAssociationCoreDtosUserUserResponse.email);
        writer.writeStringValue("firebaseId", sSTAlumniAssociationCoreDtosUserUserResponse.firebaseId);
        writer.writeStringValue("id", sSTAlumniAssociationCoreDtosUserUserResponse.id);
        writer.writeStringValue("name", sSTAlumniAssociationCoreDtosUserUserResponse.name);
        writer.writeBooleanValue("revoked", sSTAlumniAssociationCoreDtosUserUserResponse.revoked);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationCoreDtosUserUserResponseWrapper(writer: SerializationWriter, sSTAlumniAssociationCoreDtosUserUserResponseWrapper: Partial<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationCoreDtosUserUserResponseWrapper === undefined || sSTAlumniAssociationCoreDtosUserUserResponseWrapper === null) return;
    switch (sSTAlumniAssociationCoreDtosUserUserResponseWrapper.discriminator) {
        case "AlumniMember":
            serializeSSTAlumniAssociationCoreDtosUserAlumniMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserAlumniMemberResponse);
            break;
        case "Employee":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserEmployeeResponse);
            break;
        case "EmployeeMember":
            serializeSSTAlumniAssociationCoreDtosUserEmployeeMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse);
            break;
        case "Member":
            serializeSSTAlumniAssociationCoreDtosUserMemberResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserMemberResponse);
            break;
        case "ServiceAccount":
            serializeSSTAlumniAssociationCoreDtosUserServiceAccountResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserServiceAccountResponse);
            break;
        case "SystemAdmin":
            serializeSSTAlumniAssociationCoreDtosUserSystemAdminResponse(writer, sSTAlumniAssociationCoreDtosUserUserResponseWrapper as SSTAlumniAssociationCoreDtosUserSystemAdminResponse);
            break;
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse) {
        writer.writeStringValue("ctaTitle", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.ctaTitle);
        writer.writeStringValue("ctaUrl", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.ctaUrl);
        writer.writeStringValue("description", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.description);
        writer.writeStringValue("heroImageAlt", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.heroImageAlt);
        writer.writeStringValue("heroImageUrl", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.heroImageUrl);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.id);
        writer.writeStringValue("title", sSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse) {
        writer.writeStringValue("admissionKey", sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admissionKey);
        writer.writeDateValue("admittedAt", sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admittedAt);
        writer.writeObjectValue<SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse>("admittedBy", sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.admittedBy, serializeSSTAlumniAssociationCoreDtosUserUserResponseWrapper);
        writer.writeObjectValue<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse>("event", sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.event, serializeSSTAlumniAssociationMemberWebApiEndpointsEventEventResponse);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest) {
        writer.writeStringValue("email", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest.email);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse) {
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.id);
        writer.writeBooleanValue("linked", sSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse.linked);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse) {
        writer.writeDateValue("checkInDateTime", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkInDateTime);
        writer.writeDateValue("checkOutDateTime", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.checkOutDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSSTAlumniAssociationMemberWebApiEndpointsEventEventResponse(writer: SerializationWriter, sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse: Partial<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse> | undefined | null = {}) : void {
    if (sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse) {
        writer.writeBooleanValue("active", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.active);
        writer.writeStringValue("badgeImage", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.badgeImage);
        writer.writeStringValue("description", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.description);
        writer.writeDateValue("endDateTime", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.endDateTime);
        writer.writeStringValue("id", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.id);
        writer.writeStringValue("location", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.location);
        writer.writeStringValue("name", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.name);
        writer.writeDateValue("startDateTime", sSTAlumniAssociationMemberWebApiEndpointsEventEventResponse.startDateTime);
    }
}
export interface SSTAlumniAssociationCoreDtosUserAlumniMemberResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserMemberResponse {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The graduationYear property
     */
    graduationYear?: number | null;
}
export interface SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserMemberResponse {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The graduationYear property
     */
    graduationYear?: number | null;
}
export interface SSTAlumniAssociationCoreDtosUserEmployeeResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserUserResponse {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface SSTAlumniAssociationCoreDtosUserMemberResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserUserResponse {
    /**
     * The activeSubscription property
     */
    activeSubscription?: SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse | null;
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The memberId property
     */
    memberId?: string | null;
}
export interface SSTAlumniAssociationCoreDtosUserMembershipPlanResponse extends Parsable {
    /**
     * The builtIn property
     */
    builtIn?: boolean | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The duration property
     */
    duration?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
}
export interface SSTAlumniAssociationCoreDtosUserMembershipSubscriptionResponse extends Parsable {
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The membershipPlan property
     */
    membershipPlan?: SSTAlumniAssociationCoreDtosUserMembershipPlanResponse | null;
    /**
     * The paymentIntentId property
     */
    paymentIntentId?: string | null;
    /**
     * The paymentIntentState property
     */
    paymentIntentState?: number | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface SSTAlumniAssociationCoreDtosUserServiceAccountResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserUserResponse {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The serviceAccountType property
     */
    serviceAccountType?: number | null;
}
export interface SSTAlumniAssociationCoreDtosUserSystemAdminResponse extends AdditionalDataHolder, Parsable, SSTAlumniAssociationCoreDtosUserUserResponse {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface SSTAlumniAssociationCoreDtosUserUserResponse extends Parsable {
    /**
     * The discriminator property
     */
    discriminator?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The firebaseId property
     */
    firebaseId?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The revoked property
     */
    revoked?: boolean | null;
}
export type SSTAlumniAssociationCoreDtosUserUserResponseWrapper = SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse;
export interface SSTAlumniAssociationMemberWebApiEndpointsArticleArticleResponse extends Parsable {
    /**
     * The ctaTitle property
     */
    ctaTitle?: string | null;
    /**
     * The ctaUrl property
     */
    ctaUrl?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The heroImageAlt property
     */
    heroImageAlt?: string | null;
    /**
     * The heroImageUrl property
     */
    heroImageUrl?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse extends Parsable {
    /**
     * The admissionKey property
     */
    admissionKey?: string | null;
    /**
     * The admittedAt property
     */
    admittedAt?: Date | null;
    /**
     * The admittedBy property
     */
    admittedBy?: SSTAlumniAssociationCoreDtosUserAlumniMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeMemberResponse | SSTAlumniAssociationCoreDtosUserEmployeeResponse | SSTAlumniAssociationCoreDtosUserMemberResponse | SSTAlumniAssociationCoreDtosUserServiceAccountResponse | SSTAlumniAssociationCoreDtosUserSystemAdminResponse | null;
    /**
     * The event property
     */
    event?: SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse | null;
    /**
     * The id property
     */
    id?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsAuthVerifyPostVerifyResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The linked property
     */
    linked?: boolean | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsCheckInCheckInResponse extends Parsable {
    /**
     * The checkInDateTime property
     */
    checkInDateTime?: Date | null;
    /**
     * The checkOutDateTime property
     */
    checkOutDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
}
export interface SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse extends Parsable {
    /**
     * The active property
     */
    active?: boolean | null;
    /**
     * The badgeImage property
     */
    badgeImage?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
/* tslint:enable */
/* eslint-enable */
