/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event/{id}/Attendee
 */
export interface AttendeeRequestBuilder extends BaseRequestBuilder<AttendeeRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AttendeeRequestBuilderUriTemplate = "{+baseurl}/Event/{id}/Attendee";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttendeeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AttendeeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsAttendeeGetAttendeeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
