/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { WithAttendeeItemRequestBuilderRequestsMetadata, type WithAttendeeItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Attendee
 */
export interface AttendeeRequestBuilder extends BaseRequestBuilder<AttendeeRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Attendee.item collection
     * @param attendeeId Unique identifier of the item
     * @returns {WithAttendeeItemRequestBuilder}
     */
     byAttendeeId(attendeeId: string) : WithAttendeeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AttendeeRequestBuilderUriTemplate = "{+baseurl}/Attendee";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AttendeeRequestBuilderNavigationMetadata: Record<Exclude<keyof AttendeeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAttendeeId: {
        requestsMetadata: WithAttendeeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["AttendeeId"],
    },
};
/* tslint:enable */
/* eslint-enable */
