/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsUserUserResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /User/{id}/Bind
 */
export interface BindRequestBuilder extends BaseRequestBuilder<BindRequestBuilder> {
    /**
     * Bind user to a Firebase ID. Although this can also be done in the UpdateUser route, due to the differentpermission requirement for updating FirebaseId, it would introduce a partial success state for the endpoint (whereonly the FirebaseId is updated of all fields provided in the UpdateMask). Therefore, a separate route exists forthis specific use case. This route should be called by end-users only (not admins) as it will bind the user IDprovided to the current authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsUserUserResponse | undefined>;
    /**
     * Bind user to a Firebase ID. Although this can also be done in the UpdateUser route, due to the differentpermission requirement for updating FirebaseId, it would introduce a partial success state for the endpoint (whereonly the FirebaseId is updated of all fields provided in the UpdateMask). Therefore, a separate route exists forthis specific use case. This route should be called by end-users only (not admins) as it will bind the user IDprovided to the current authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BindRequestBuilderUriTemplate = "{+baseurl}/User/{id}/Bind";
/**
 * Metadata for all the requests in the request builder.
 */
export const BindRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BindRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsUserUserResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
