/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEventFromDiscriminatorValue, createListEventAttendeesResponseFromDiscriminatorValue, createStatusFromDiscriminatorValue, type Event, type ListEventAttendeesResponse, type Status } from '../../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/events/{id}/attendees
 */
export interface AttendeesRequestBuilder extends BaseRequestBuilder<AttendeesRequestBuilder> {
    /**
     * Get an events attendees
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListEventAttendeesResponse>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ListEventAttendeesResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Event>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     post(requestConfiguration?: RequestConfiguration<AttendeesRequestBuilderPostQueryParameters> | undefined) : Promise<Event | undefined>;
    /**
     * Get an events attendees
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<AttendeesRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface AttendeesRequestBuilderPostQueryParameters {
    user?: string;
}
/**
 * Uri template for the request builder.
 */
export const AttendeesRequestBuilderUriTemplate = "{+baseurl}/v1/events/{id}/attendees";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttendeesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AttendeesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createListEventAttendeesResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AttendeesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEventFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
