/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue, type SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse } from '../models/index.js';
// @ts-ignore
import { EventItemRequestBuilderNavigationMetadata, EventItemRequestBuilderRequestsMetadata, type EventItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Event
 */
export interface EventRequestBuilder extends BaseRequestBuilder<EventRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Event.item collection
     * @param id Unique identifier of the item
     * @returns {EventItemRequestBuilder}
     */
     byId(id: string) : EventItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SSTAlumniAssociationMemberWebApiEndpointsEventEventResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EventRequestBuilderUriTemplate = "{+baseurl}/Event";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EventRequestBuilderNavigationMetadata: Record<Exclude<keyof EventRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: EventItemRequestBuilderRequestsMetadata,
        navigationMetadata: EventItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EventRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EventRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSSTAlumniAssociationMemberWebApiEndpointsEventEventResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
