/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEventFromDiscriminatorValue, createStatusFromDiscriminatorValue, type Event, type Status } from '../../../models/';
// @ts-ignore
import { AttendeesRequestBuilderNavigationMetadata, AttendeesRequestBuilderRequestsMetadata, type AttendeesRequestBuilder } from './attendees/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/events/{id}
 */
export interface EventsItemRequestBuilder extends BaseRequestBuilder<EventsItemRequestBuilder> {
    /**
     * The attendees property
     */
    get attendees(): AttendeesRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Event>}
     * @throws {Status} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Event | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EventsItemRequestBuilderUriTemplate = "{+baseurl}/v1/events/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EventsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof EventsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attendees: {
        requestsMetadata: AttendeesRequestBuilderRequestsMetadata,
        navigationMetadata: AttendeesRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EventsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EventsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createStatusFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEventFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
