/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckOutRequestBuilderRequestsMetadata, type CheckOutRequestBuilder } from './checkOut/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /CheckIn/{Id}
 */
export interface CheckInItemRequestBuilder extends BaseRequestBuilder<CheckInItemRequestBuilder> {
    /**
     * The CheckOut property
     */
    get checkOut(): CheckOutRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CheckInItemRequestBuilderUriTemplate = "{+baseurl}/CheckIn/{Id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CheckInItemRequestBuilderNavigationMetadata: Record<Exclude<keyof CheckInItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkOut: {
        requestsMetadata: CheckOutRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
