name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: 📦 Install dependencies
        working-directory: SSTAlumniAssociation.WebApp
        run: pnpm install --frozen-lockfile

      - name: 🚧 Set up project
        working-directory: SSTAlumniAssociation.WebApp
        run: pnpm nuxi prepare

      - name: 📝 Lint
        run: pnpm lint

      - name: 💪 Type check
        working-directory: SSTAlumniAssociation.WebApp
        run: pnpm typecheck
